database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  app_db_name: 'dbostest'
  app_db_client: 'pg-node'
  connectionTimeoutMillis: 3000
telemetry:
  logs:
    logLevel: 'debug'
    addContextMetadata: true
    silent: true
application:
  testvalue: 'postgres'
