database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  connectionTimeoutMillis: 3000
  user_database: 'operon'
  system_database: 'operon_systemdb'
telemetryExporters:
  - 'ConsoleExporter'
  - 'PostgresExporter'
