database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  user_database: 'hello'
  connectionTimeoutMillis: 3000
telemetryExporters:
  - 'ConsoleExporter'
application:
  foo:
    bar: ${BAR:default}
  baz: 'y'
  animals:
    - type: 'turtle'
      name: 'fifi'
      age: 15
operonCloud:
  secretEnvVars:
    - 'foo'
