database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  user_database: 'hello'
  connectionTimeoutMillis: 3000
telemetryExporters:
  - 'ConsoleExporter'
application:
  foo:
    bar: 'x'
  baz: 'y'
localRuntime:
    port: 3000
operonCloud:
  secretEnvVars:
    - 'foo'
