name: Create DBOS Package Artifact

on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0 # fetch-depth 0 needed for NBGV
      - name: Use Node.js 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - name: Nerdbank.GitVersioning
        id: nbgv
        uses: dotnet/nbgv@v0.4.2
        with:
          stamp: package.json
      - run: npm ci
      - run: npm run build
      - run: npm publish
        # boolean properties from NBGV step appears to be converted into *capitalized* strings
        # so explicitly string compare PublicRelease output value
        if: ${{ steps.nbgv.outputs.PublicRelease == 'True'}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm pack
      - name: Upload package
        uses: actions/upload-artifact@v4.3.1
        with:
          name: dbos-workflow
          path: ./dbos-inc-workflow-*.tgz
