name: On Push

on:
  push:
    branches:
      - main
      - release/*

jobs:
  test:
    uses: ./.github/workflows/test.yml
  artifact:
    uses: ./.github/workflows/artifact.yml
  publish:
    uses:  ./.github/workflows/publish.yml