name: On Push

on:
  push:
    branches:
      - main
      - release/*

jobs:
  test:
    uses: ./.github/workflows/test.yml
  artifact:
    needs: test
    uses: ./.github/workflows/artifact.yml
  publish:
    runs-on: ubuntu-latest
    needs: artifact
    steps:
    - name: Download Operon
      uses: actions/download-artifact@v3
      with:
        name: operon
        path: ./
    - name: Publish to GitHub package manager
      run: |
        npm config set @dbos-inc:registry https://npm.pkg.github.com
        npm publish ${{ needs.artifact.outputs.PackageName }}
      env:
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    