name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - release/*
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
  test:
    uses: ./.github/workflows/test.yml
  artifact:
    needs: test
    uses: ./.github/workflows/artifact.yml
  echo:
    runs-on: ubuntu-latest
    needs: artifact
    steps:
      - run: echo 'NpmPackageVersion=${{ needs.artifact.outputs.NpmPackageVersion }}'
      - run: echo 'PackageName=${{ needs.artifact.outputs.PackageName }}'
