name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - release/*
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
  # temp comment out test
  # test:
  #   uses: ./.github/workflows/test.yml
  artifact:
    # needs: test
    uses: ./.github/workflows/artifact.yml
