name: On Pull Request

on:
  pull_request:
    branches:
      - main
      - release/*
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
  # temporary bypass test job
  # test:
  #   uses: ./.github/workflows/test.yml
  artifact:
    # needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/artifact.yml
