name: Publish Operon

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # fetch-depth 0 needed for NBGV
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
        # .NET 6 needed for NBGV
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Set Version 
        working-directory: ./
        run: |
          npm run setversion
      - name: Compile 
        working-directory: ./
        run: |
          npm ci
          npm run build
      - name: Publish to GitHub package manager
        working-directory: ./
        run: |
          npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

