name: Test DBOS

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Postgres service container
      postgres:
        image: postgres:16.1
        env:
          # Specify the password for Postgres superuser.
          POSTGRES_PASSWORD: dbos
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      # Kafka service container
      kafka:
        image: bitnami/kafka:latest
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_LISTENERS: PLAINTEXT_INTERNAL://:9093,PLAINTEXT_EXTERNAL://:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:9093,PLAINTEXT_EXTERNAL://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
          ALLOW_PLAINTEXT_LISTENER: "yes"
        options: >-
          --health-cmd "timeout 5 nc -z localhost 9092"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 9092:9092
      # Zookeeper service container, required for Kafka
      zookeeper:
        image: bitnami/zookeeper:latest
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"
        options: >-
          --health-cmd "timeout 5 nc -z localhost 2181"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 2181:2181

    steps:
      - name: "Setup postgres config"
        run: |
          docker exec -i ${{ job.services.postgres.id }} apt update
          docker exec ${{ job.services.postgres.id }} sh -c 'echo "wal_level=logical" >> /var/lib/postgresql/data/postgresql.conf'
          docker restart ${{ job.services.postgres.id }}
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js 20
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Compile and Test
        working-directory: ./
        run: |
          npm ci
          npm run build
          npm test
          npm run lint
        env:
          PGPASSWORD: dbos
          DB_PASSWORD: dbos
          DB_USER: postgres
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SILENCE_LOGS: true
